### ISSUE TITLE
undefined method `build_form_from'

### ISSUE THREAD

**Issue by arnoldmarunda** [useed/typed_form#18]
I obtain the following error
`undefined method `build_form_from' for TypedForm::Form:Class (NoMethodError)`

**Comment by robcole** [comment]
Looks like an error in my documentation - sorry about that! Try this instead - I'll update the docs as well, but you should be able to use `TypedForm::Form.new(json: your_json_data)` instead of `TypedForm::Form.build_form_from(json: your_json_data)` in the meantime.

**Comment by arnoldmarunda** [comment]
I now get this error
**`/ruby/gems/typed_form-0.1.6/lib/typed_form/util.rb:7:in `normalize_spaces': undefined method `gsub'**

**Comment by arnoldmarunda** [comment]
Sorry did not give the full error
ruby/gems/typed_form-0.1.6/lib/typed_form/util.rb:7:in `normalize_spaces': undefined method `gsub' for #<Hash:0x007fd292190160> (NoMethodError)
        from .rvm/rubies/ruby/gems/typed_form-0.1.6/lib/typed_form/form.rb:27:in `json'
        from .rvm/rubies/ruby/gems/typed_form-0.1.6/lib/typed_form/form.rb:66:in `parsed_json'
        from .rvm/rubies/ruby/gems/typed_form-0.1.6/lib/typed_form/form.rb:56:in `submission'

**Comment by robcole** [comment]
It looks like you're passing a Hash (probably via parsing JSON) instead of JSON - try passing in the RAW JSON instead.

**Comment by arnoldmarunda** [comment]
@robcole this could prove to be a very useful gem. Thank you

**Comment by robcole** [comment]
Thanks! I'm looking at adding a few more API-centric features (mostly just to do with data loading) sometime in the not-so-distant future, but if there's any other features you think would make it more useful, let me know and if it makes sense to add them I'll see what I can do. 👍
